import { NextResponse } from 'next/server';
import React from 'react';
import { renderToStream } from '@react-pdf/renderer';
import ResumeDocument from '@/components/resume/ResumeDocument';
import { client } from '@/sanity/lib/client';
import { Resend } from 'resend';

// Initialize Resend with fallback (prevents crash if key is missing)
const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

// Helper: Convert Stream to Buffer
async function streamToBuffer(stream) {
    const chunks = [];
    for await (const chunk of stream) {
        chunks.push(chunk);
    }
    return Buffer.concat(chunks);
}

export async function POST(req) {
    try {
        console.log("1. Resume Request Received");
        const body = await req.json();
        const { name, email, purpose } = body;
        console.log("2. Request parsed:", { name, email, purpose });

        // 1. Log to Sanity (CRM - Contact Schema)
        const token = process.env.SANITY_API_WRITE_TOKEN;
        console.log("3. Sanity Token Present:", !!token);

        if (token) {
            const writeClient = client.withConfig({ token, useCdn: false });
            await writeClient.create({
                _type: 'contact',
                name: name || 'Anonymous',
                email: email || 'No Email',
                type: 'resume',
                message: purpose || 'Unknown',
                status: 'new',
                createdAt: new Date().toISOString()
            }).catch(err => console.error("Sanity Write Error:", err));
        }

        // 2. Fetch Data
        const query = `{
          "about": *[_type == "about"][0],
          "settings": *[_type == "settings"][0]
        }`;

        console.log("4. Fetching content data...");
        const data = await client.fetch(query);
        console.log("5. Data fetched:", !!data);

        const authorName = data.settings?.authorName || 'Hazem Gamal';
        const role = data.settings?.authorRole || 'Product Designer';
        const portfolioUrl = 'https://7azempro.vercel.app';

        // 3. Generate PDF Buffer via Stream (Safer Compatibility)
        console.log("6. Starting PDF Rendering...");
        const stream = await renderToStream(<ResumeDocument data={data} />);
        console.log("7. PDF Rendering stream created, converting to buffer...");
        const pdfBuffer = await streamToBuffer(stream);
        console.log("8. Buffer created, size:", pdfBuffer.length);

        // 4. Send Emails (if Resend is configured)
        if (resend) {
            console.log("9. Resend configured, preparing emails...");
            const emailsToSend = [];

            // A. Admin Alert
            if (data.settings?.contactEmail) {
                emailsToSend.push(resend.emails.send({
                    from: 'System Log <noreply@24tech.sa>',
                    to: data.settings.contactEmail,
                    subject: `[Resume Access] New Download by ${name}`,
                    html: `
                        <div style="font-family: monospace; padding: 20px; background: #f5f5f5;">
                            <h2>System Access Alert</h2>
                            <p><strong>User:</strong> ${name}</p>
                            <p><strong>Email:</strong> ${email}</p>
                            <p><strong>Purpose:</strong> ${purpose}</p>
                            <p><strong>Time:</strong> ${new Date().toLocaleString()}</p>
                            <hr/>
                            <p style="font-size: 10px; color: #666;">Generated by 7azempro System</p>
                        </div>
                    `
                }));
            }

            // B. User Confirmation (Swiss Theme)
            if (email && email.includes('@')) {
                const emailHtml = `
                <!DOCTYPE html>
                <html>
                <head>
                    <style>
                        body { font-family: 'Courier New', Courier, monospace; background-color: #f4f4f5; padding: 40px 20px; margin: 0; }
                        .container { max-width: 600px; margin: 0 auto; background: #ffffff; padding: 40px; border: 1px solid #e4e4e7; }
                        .header { border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 30px; }
                        .logo { font-weight: 900; letter-spacing: -1px; font-size: 24px; text-transform: uppercase; display: block; margin-bottom: 10px; color: #000; text-decoration: none;}
                        .meta { font-size: 10px; color: #71717a; text-transform: uppercase; letter-spacing: 1px; }
                        .content { line-height: 1.6; color: #18181b; font-size: 14px; margin-bottom: 40px; }
                        .btn { display: inline-block; background: #000; color: #fff; padding: 12px 24px; text-decoration: none; font-size: 11px; text-transform: uppercase; letter-spacing: 2px; font-weight: bold; margin-top: 20px; }
                        .footer { border-top: 1px solid #e4e4e7; padding-top: 20px; font-size: 10px; color: #a1a1aa; display: flex; justify-content: space-between; }
                        .link { color: #000; text-decoration: none; font-weight: bold; margin-right: 15px; }
                    </style>
                </head>
                <body>
                    <div class="container">
                        <div class="header">
                            <a href="${portfolioUrl}" class="logo">7AZEM.PRO</a>
                            <div class="meta">System Automated Response // ID: ${Date.now().toString(36).toUpperCase()}</div>
                        </div>
                        
                        <div class="content">
                            <p><strong>RE: DOCUMENT REQUEST // ${name.toUpperCase()}</strong></p>
                            <p>Access request received. The biographical data package you requested has been generated and attached to this transmission.</p>
                            <p>This document reflects the current snapshot of my professional architecture, skills, and project history.</p>
                            
                            <br/>
                            <p style="border-left: 2px solid #000; padding-left: 15px;">
                                "Design is not just what it looks like and feels like. Design is how it works."
                            </p>
                            
                            <a href="${portfolioUrl}" class="btn">Return to Signal</a>
                        </div>
                        
                        <div class="footer">
                            <div>
                                <div style="margin-bottom: 10px; font-weight: bold; color: #000;">ESTABLISH COMM_LINK:</div>
                                <a href="https://www.linkedin.com/in/7azempro" class="link">LINKEDIN</a>
                                <a href="https://linktr.ee/7azempro" class="link">LINKTREE</a>
                                <a href="mailto:${data.settings?.contactEmail}" class="link">EMAIL</a>
                                <a href="${portfolioUrl}/works" class="link">ARCHIVE</a>
                            </div>
                            <div style="text-align: right;">
                                ${role.toUpperCase()}<br/>
                                CAIRO, EG<br/>
                                ${new Date().getFullYear()}
                            </div>
                        </div>
                    </div>
                </body>
                </html>
                `;

                emailsToSend.push(resend.emails.send({
                    from: `${authorName} <noreply@24tech.sa>`,
                    to: email,
                    subject: `ACCESS GRANTED: ${authorName} Bio-Data`,
                    html: emailHtml,
                    attachments: [
                        {
                            filename: `${authorName.replace(/\s+/g, '_')}_Resume.pdf`,
                            content: pdfBuffer
                        }
                    ]
                }));
            }

            const results = await Promise.allSettled(emailsToSend);

            // Log results for debugging
            results.forEach((result, index) => {
                if (result.status === 'rejected') {
                    const err = result.reason;
                    if (err?.statusCode === 403 && err?.message?.includes('testing emails')) {
                        console.warn(`[Resend Test Mode] Blocked email to recipient ${index + 1}. You must verify your domain to send to external addresses.`);
                    } else {
                        console.error(`[Resend Error] Email ${index + 1} failed:`, err);
                    }
                }
            });
        }

        // 5. Return PDF Response
        return new NextResponse(pdfBuffer, {
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `attachment; filename="${authorName.replace(/\s+/g, '_')}_Resume.pdf"`,
            },
        });

    } catch (error) {
        console.error('PDF Generation Error:', error);
        return NextResponse.json({
            error: 'Failed to generate PDF',
            details: error.message,
            stack: error.stack
        }, { status: 500 });
    }
}
