import { RiFileUserLine } from "react-icons/ri";

export const resumeLog = {
    name: 'resumeLog',
    title: 'Resume Download Log',
    type: 'document',
    icon: RiFileUserLine,
    readOnly: true, // Generated by system, not editable manually
    fields: [
        {
            name: 'name',
            title: 'Name',
            type: 'string',
        },
        {
            name: 'email',
            title: 'Email',
            type: 'string',
        },
        {
            name: 'purpose',
            title: 'Purpose',
            type: 'string',
        },
        {
            name: 'downloadedAt',
            title: 'Time of Access',
            type: 'datetime',
        }
    ],
    preview: {
        select: {
            title: 'name',
            subtitle: 'purpose',
            date: 'downloadedAt'
        },
        prepare({ title, subtitle, date }) {
            return {
                title: title || 'Anonymous',
                subtitle: `${subtitle} • ${date ? new Date(date).toLocaleDateString() : 'Just now'}`,
                media: RiFileUserLine
            }
        }
    }
}
